// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelTransfer(arg1:string):Promise<void>;

export function CreateRemoteDir(arg1:string,arg2:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetRemotePwd(arg1:string):Promise<string>;

export function GetTransferProgress(arg1:string):Promise<main.TransferProgress>;

export function ListRemoteDir(arg1:string,arg2:string):Promise<Array<main.RemoteFile>>;

export function RenameRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<string>;
