// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer(arg1) {
  return window['go']['main']['FileManager']['CancelTransfer'](arg1);
}

export function CreateRemoteDir(arg1, arg2) {
  return window['go']['main']['FileManager']['CreateRemoteDir'](arg1, arg2);
}

export function DeleteRemoteFile(arg1, arg2) {
  return window['go']['main']['FileManager']['DeleteRemoteFile'](arg1, arg2);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['FileManager']['DownloadFile'](arg1, arg2, arg3);
}

export function GetRemotePwd(arg1) {
  return window['go']['main']['FileManager']['GetRemotePwd'](arg1);
}

export function GetTransferProgress(arg1) {
  return window['go']['main']['FileManager']['GetTransferProgress'](arg1);
}

export function ListRemoteDir(arg1, arg2) {
  return window['go']['main']['FileManager']['ListRemoteDir'](arg1, arg2);
}

export function RenameRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['FileManager']['RenameRemoteFile'](arg1, arg2, arg3);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['FileManager']['UploadFile'](arg1, arg2, arg3);
}
