// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['main']['ProfilesManager']['DeleteProfile'](arg1);
}

export function ExportProfiles(arg1, arg2) {
  return window['go']['main']['ProfilesManager']['ExportProfiles'](arg1, arg2);
}

export function GetProfile(arg1) {
  return window['go']['main']['ProfilesManager']['GetProfile'](arg1);
}

export function ImportProfiles(arg1, arg2) {
  return window['go']['main']['ProfilesManager']['ImportProfiles'](arg1, arg2);
}

export function ListProfiles() {
  return window['go']['main']['ProfilesManager']['ListProfiles']();
}

export function Paths() {
  return window['go']['main']['ProfilesManager']['Paths']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['ProfilesManager']['SaveProfile'](arg1);
}
