// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteProfile(arg1:string):Promise<void>;

export function ExportProfiles(arg1:string,arg2:string):Promise<void>;

export function GetProfile(arg1:string):Promise<main.HostProfile>;

export function ImportProfiles(arg1:string,arg2:string):Promise<number>;

export function ListProfiles():Promise<Array<main.HostProfile>>;

export function Paths():Promise<Record<string, string>>;

export function SaveProfile(arg1:main.HostProfile):Promise<string>;
