// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['main']['TermManager']['Close'](arg1);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['main']['TermManager']['Resize'](arg1, arg2, arg3);
}

export function Send(arg1, arg2) {
  return window['go']['main']['TermManager']['Send'](arg1, arg2);
}

export function StartLocalForward(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['TermManager']['StartLocalForward'](arg1, arg2, arg3, arg4, arg5);
}

export function StartRecording(arg1, arg2, arg3) {
  return window['go']['main']['TermManager']['StartRecording'](arg1, arg2, arg3);
}

export function StartSSH(arg1) {
  return window['go']['main']['TermManager']['StartSSH'](arg1);
}

export function StartWebProxy(arg1, arg2, arg3, arg4) {
  return window['go']['main']['TermManager']['StartWebProxy'](arg1, arg2, arg3, arg4);
}

export function StartWebProxyViaSSH(arg1, arg2, arg3, arg4) {
  return window['go']['main']['TermManager']['StartWebProxyViaSSH'](arg1, arg2, arg3, arg4);
}

export function StopLocalForward(arg1, arg2) {
  return window['go']['main']['TermManager']['StopLocalForward'](arg1, arg2);
}

export function StopRecording(arg1) {
  return window['go']['main']['TermManager']['StopRecording'](arg1);
}
