// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close(arg1:string):Promise<void>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Send(arg1:string,arg2:string):Promise<void>;

export function StartLocalForward(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number):Promise<string>;

export function StartRecording(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function StartSSH(arg1:main.SSHParams):Promise<string>;

export function StartWebProxy(arg1:string,arg2:number,arg3:string,arg4:number):Promise<string>;

export function StartWebProxyViaSSH(arg1:string,arg2:number,arg3:string,arg4:number):Promise<string>;

export function StopLocalForward(arg1:string,arg2:string):Promise<void>;

export function StopRecording(arg1:string):Promise<void>;
